import { FC, PropsWithChildren } from 'react';
import './index.css';
import { Header } from '@/components/Header';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
    <html lang="en">
        <body>
            <Header />
            {children}
        </body>
    </html>
);

export default RootLayout;
