'use client';

import { FC, PropsWithChildren } from 'react';
import './index.css';
import { Header } from '@/components/Header';
import { trpc } from '@/common/trpc';
import { SessionProvider } from 'next-auth/react';
import { Session } from 'next-auth';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren<{ session: Session }>> = ({ children, session }) => (
    <html lang="en">
        <body>
            <SessionProvider session={session}>
                <Header />
                {children}
            </SessionProvider>
        </body>
    </html>
);

export default trpc.react.withTRPC(RootLayout);
